export type PostCategory =
  | "desain"
  | "development"
  | "seo"
  | "studi-kasus"
  | "bisnis";

export interface BlogPost {
  slug: string;
  title: string;
  excerpt: string;
  category: PostCategory;
  categoryLabel: string;
  date: string;        // ISO string
  readTime: number;    // minutes
  coverColor: string;  // placeholder bg colour
  content: ContentBlock[];
}

export type ContentBlock =
  | { type: "p";   text: string }
  | { type: "h2";  text: string }
  | { type: "h3";  text: string }
  | { type: "ul";  items: string[] }
  | { type: "ol";  items: string[] }
  | { type: "quote"; text: string; author?: string }
  | { type: "callout"; text: string };

export const postCategories: { label: string; value: "semua" | PostCategory }[] = [
  { label: "Semua",       value: "semua"      },
  { label: "Desain",      value: "desain"      },
  { label: "Development", value: "development" },
  { label: "SEO",         value: "seo"         },
  { label: "Studi Kasus", value: "studi-kasus" },
  { label: "Bisnis",      value: "bisnis"      },
];

export const posts: BlogPost[] = [
  {
    slug: "rebuild-brand-fashion-2-minggu",
    title: "Bagaimana kami membangun ulang website brand fashion lokal dalam 2 minggu",
    excerpt: "Dari riset kompetitor sampai landing page yang menaikkan konversi 3× — ini proses lengkap di balik salah satu project favorit tim kami.",
    category: "studi-kasus",
    categoryLabel: "Studi Kasus",
    date: "2026-08-12",
    readTime: 6,
    coverColor: "#f9e0de",
    content: [
      { type: "p", text: "Klien kami adalah brand fashion lokal asal Bandung yang sudah berjalan 3 tahun tapi website mereka masih stuck di template gratisan dari 2020. Conversion rate mereka di bawah 0.8% — jauh di bawah rata-rata industri fashion yang bisa mencapai 2–3%." },
      { type: "h2", text: "Hari 1–3: Riset & Audit" },
      { type: "p", text: "Sebelum menulis satu baris kode pun, kami habiskan tiga hari pertama untuk riset. Kami analisis 5 kompetitor langsung, lihat heat map halaman lama klien, dan wawancara 8 pelanggan mereka via WhatsApp." },
      { type: "ul", items: [
        "Pengunjung mobile mencapai 78% dari total traffic, tapi bounce rate mobile 3× lebih tinggi dari desktop",
        "Foto produk terlalu kecil di mobile — susah dilihat detail tekstur kain",
        "Proses checkout butuh 6 langkah, kebanyakan drop di langkah ke-3",
        "Tidak ada social proof di halaman produk",
      ]},
      { type: "h2", text: "Hari 4–8: Desain & Prototyping" },
      { type: "p", text: "Kami putuskan untuk rebuild dari nol, bukan revamp. Template lama terlalu banyak technical debt. Dengan timeline 2 minggu, kami fokus hanya pada halaman yang paling berpengaruh ke konversi: landing page, halaman produk, dan checkout." },
      { type: "quote", text: "Jangan desain semua halaman dengan effort yang sama. Identifikasi 3 halaman yang paling berdampak ke revenue, dan habiskan 80% energi di sana.", author: "Prinsip yang kami pakai di setiap project" },
      { type: "p", text: "Sistem desain kami buat simpel: 2 typeface, 4 warna utama, dan komponen yang bisa di-reuse. Ini yang bikin kami bisa bergerak cepat tanpa kehilangan konsistensi visual." },
      { type: "h2", text: "Hari 9–12: Development" },
      { type: "p", text: "Stack yang kami pilih: Next.js 14 dengan App Router, Tailwind untuk styling, dan Shopify Storefront API untuk inventory. Keputusan ini memungkinkan klien mengelola produk sendiri tanpa perlu akses ke kode." },
      { type: "ul", items: [
        "Image optimization otomatis lewat Next.js — foto produk dari 4MB turun ke rata-rata 180KB",
        "Checkout disederhanakan jadi 2 langkah dengan progress indicator",
        "Review produk dari WhatsApp dikonversi jadi social proof cards",
        "Core Web Vitals: LCP di bawah 1.8s, CLS 0",
      ]},
      { type: "h2", text: "Hari 13–14: QA & Launch" },
      { type: "p", text: "Dua hari terakhir full testing: cross-browser, cross-device, performance audit, dan dry-run proses pembelian dari awal sampai konfirmasi order. Kami launch di hari Jumat malam untuk menghindari traffic peak." },
      { type: "callout", text: "Hasilnya setelah 30 hari: conversion rate naik dari 0.8% ke 2.6%, rata-rata order value naik 18%, dan bounce rate mobile turun dari 74% ke 41%." },
      { type: "h2", text: "Pelajaran yang Bisa Diambil" },
      { type: "ol", items: [
        "Riset pengguna selalu lebih berharga dari asumsi desainer — 3 hari riset menghemat 3 minggu revisi",
        "Mobile-first bukan slogan, ini kebutuhan nyata untuk bisnis fashion Indonesia",
        "Simplifikasi checkout adalah quick win terbesar untuk e-commerce lokal",
        "Social proof dalam bahasa lokal (screenshot WA, foto pembeli) lebih dipercaya dari bintang rating",
      ]},
    ],
  },
  {
    slug: "5-kesalahan-layout-murah",
    title: "5 kesalahan layout yang bikin website terlihat murah",
    excerpt: "Bukan soal warna atau font mahal — ini pola kecil yang paling sering luput dan perhatian tim desain pemula.",
    category: "desain",
    categoryLabel: "Desain",
    date: "2026-08-04",
    readTime: 4,
    coverColor: "#fce8e8",
    content: [
      { type: "p", text: "Setelah review ratusan website klien, kami menemukan pola yang berulang. Website yang terlihat 'murah' bukan karena warnanya jelek atau fontnya tidak premium — tapi karena beberapa kesalahan layout yang sangat spesifik dan bisa diperbaiki hari ini." },
      { type: "h2", text: "1. Lebar Teks yang Terlalu Penuh" },
      { type: "p", text: "Paragraf yang memanjang sampai ujung layar adalah tanda paling mudah dikenali dari layout yang tidak dipikirkan. Penelitian tipografi menunjukkan teks paling nyaman dibaca pada lebar 60–75 karakter per baris." },
      { type: "callout", text: "Fix cepat: tambahkan max-width: 65ch pada elemen paragraf konten utama kamu. Itu saja sudah langsung terasa perbedaannya." },
      { type: "h2", text: "2. Spacing yang Tidak Konsisten" },
      { type: "p", text: "Gap antara elemen yang berubah-ubah tanpa ritme — kadang 12px, kadang 18px, kadang 24px — membuat mata lelah tanpa sadar. Otak manusia mencari pola, dan ketidakkonsistenan spacing membuatnya kerja ekstra." },
      { type: "ul", items: [
        "Gunakan skala 4px atau 8px: 4, 8, 12, 16, 24, 32, 48, 64",
        "Jarak antar section harus lebih besar dari jarak antar elemen dalam section",
        "White space bukan pemborosan — ini yang membuat elemen penting terlihat penting",
      ]},
      { type: "h2", text: "3. Terlalu Banyak Font Weight" },
      { type: "p", text: "Regular, medium, semibold, bold, extrabold — kalau semua dipakai dalam satu halaman, tidak ada yang terasa spesial. Hierarki visual hilang karena semua bersaing untuk perhatian." },
      { type: "h2", text: "4. Gambar Tanpa Proporsi yang Dijaga" },
      { type: "p", text: "Foto yang terstretch horizontal, thumbnail yang cropnya berbeda-beda, atau hero image yang resolusinya terlalu rendah. Ini semua sinyal bahwa detail tidak diperhatikan — dan pengguna langsung membaca ini sebagai 'tidak profesional'." },
      { type: "h2", text: "5. CTA yang Tenggelam di Halaman" },
      { type: "p", text: "Tombol Call to Action yang warnanya sama dengan background, ukurannya terlalu kecil, atau tertutup elemen lain. Kalau pengunjung harus mencari tombol untuk melakukan aksi, kamu sudah kehilangan konversi sebelum mereka sempat klik." },
      { type: "quote", text: "Design is not just what it looks like and feels like. Design is how it works.", author: "Steve Jobs" },
      { type: "p", text: "Semua kesalahan di atas punya satu benang merah: kurangnya perhatian terhadap detail. Kabar baiknya, semuanya bisa diperbaiki tanpa redesign total — hanya butuh waktu beberapa jam dan mata yang terlatih untuk melihatnya." },
    ],
  },
  {
    slug: "website-lambat-cara-memperbaiki",
    title: "Kenapa website kamu lambat, dan cara memperbaikinya",
    excerpt: "Core Web Vitals bukan cuma angka di Lighthouse — ini langkah nyata yang bisa kamu lakukan hari ini tanpa ganti stack.",
    category: "development",
    categoryLabel: "Development",
    date: "2026-07-28",
    readTime: 7,
    coverColor: "#e8f0fe",
    content: [
      { type: "p", text: "Google resmi menjadikan Core Web Vitals sebagai ranking factor sejak 2021. Tapi lebih dari sekadar SEO — website yang lambat langsung berdampak ke user experience dan konversi. Amazon pernah menghitung bahwa setiap 100ms tambahan loading time mempengaruhi revenue mereka 1%." },
      { type: "h2", text: "Metrik yang Perlu Kamu Tahu" },
      { type: "ul", items: [
        "LCP (Largest Contentful Paint): waktu elemen terbesar muncul. Target < 2.5 detik",
        "FID / INP (Interaction to Next Paint): waktu respons terhadap input pengguna. Target < 200ms",
        "CLS (Cumulative Layout Shift): seberapa banyak elemen bergeser saat loading. Target < 0.1",
      ]},
      { type: "h2", text: "Penyebab Paling Umum Website Lambat" },
      { type: "h3", text: "Gambar Tidak Dioptimasi" },
      { type: "p", text: "Ini penyebab nomor satu. Developer upload foto 4MB langsung dari kamera, lupa convert ke WebP, dan tidak pakai lazy loading. Solusinya: pakai format WebP/AVIF, resize sesuai tampilan aktual, dan tambahkan loading='lazy' pada gambar di bawah fold." },
      { type: "h3", text: "JavaScript yang Terlalu Besar" },
      { type: "p", text: "Bundle JS yang tidak di-split menyebabkan browser harus download, parse, dan compile semua kode sebelum halaman interaktif. Audit bundle kamu dengan webpack-bundle-analyzer atau Next.js bundle analyzer." },
      { type: "h3", text: "Tidak Ada Caching" },
      { type: "p", text: "Setiap kunjungan download ulang semua asset dari server. Cache-Control header yang benar bisa membuat return visitor merasakan halaman yang muncul hampir instan." },
      { type: "callout", text: "Quick win terbesar yang bisa kamu lakukan sekarang: install plugin WebP converter di WordPress atau aktifkan Next.js Image Optimization. Tes sebelum dan sesudah dengan PageSpeed Insights — hasilnya biasanya dramatis." },
      { type: "h2", text: "Langkah Perbaikan yang Terurut" },
      { type: "ol", items: [
        "Audit dulu dengan PageSpeed Insights dan WebPageTest — identifikasi bottleneck utama",
        "Optimasi gambar (konversi WebP, lazy loading, ukuran yang tepat)",
        "Aktifkan compression (Gzip/Brotli) di server",
        "Review dan kurangi third-party scripts (chat widget, analytics, pixel iklan)",
        "Implementasi caching yang benar",
        "Pertimbangkan CDN untuk asset statik",
      ]},
      { type: "p", text: "Jangan coba perbaiki semuanya sekaligus. Ukur, perbaiki satu hal, ukur lagi. Pendekatan iteratif ini lebih efektif dan memudahkan kamu tahu mana yang paling berdampak." },
    ],
  },
  {
    slug: "seo-on-page-untuk-umkm",
    title: "SEO on-page untuk UMKM: mulai dari mana?",
    excerpt: "Tanpa agency, tanpa tools berbayar — panduan langkah demi langkah untuk bisnis kecil yang ingin muncul di Google.",
    category: "seo",
    categoryLabel: "SEO",
    date: "2026-07-20",
    readTime: 5,
    coverColor: "#e8fef0",
    content: [
      { type: "p", text: "Banyak pemilik UMKM yang frustrasi karena sudah punya website tapi tidak muncul di Google. Masalahnya sering bukan di domain authority atau backlink — tapi di on-page SEO dasar yang terlewat. Kabar baiknya, ini bisa diperbaiki tanpa budget tambahan." },
      { type: "h2", text: "Mulai dari Riset Kata Kunci yang Realistis" },
      { type: "p", text: "Jangan langsung bidik kata kunci kompetitif seperti 'jasa web murah' atau 'toko online'. UMKM yang baru mulai harus fokus ke long-tail keywords yang lebih spesifik dan lebih mudah dimenangkan." },
      { type: "callout", text: "Cara gratis riset keyword: ketik topik bisnis kamu di Google, lihat bagian 'People also ask' dan 'Searches related to' di bawah hasil pencarian. Itu goldmine untuk menemukan kata kunci yang relevan dan realistis." },
      { type: "h2", text: "Optimasi yang Harus Dilakukan di Setiap Halaman" },
      { type: "ol", items: [
        "Title tag: maksimal 60 karakter, sertakan kata kunci utama di awal",
        "Meta description: 150–160 karakter, jelaskan isi halaman dengan menarik",
        "H1: satu per halaman, harus mengandung kata kunci utama",
        "URL yang bersih: /jasa-desain-logo bukan /page?id=123",
        "Alt text pada semua gambar: deskriptif, bukan 'image1.jpg'",
      ]},
      { type: "h2", text: "Konten yang Benar-Benar Menjawab Pertanyaan" },
      { type: "p", text: "Google semakin pintar membedakan konten yang genuinely helpful dengan konten yang hanya dioptimasi untuk ranking. Tulis untuk manusia dulu, bukan untuk bot. Tapi pastikan kamu menyebut kata kunci secara natural." },
      { type: "h2", text: "Google Business Profile: Senjata Tersembunyi UMKM" },
      { type: "p", text: "Untuk bisnis lokal, Google Business Profile (dulu Google My Business) sama pentingnya dengan website. Pastikan profil kamu lengkap: foto, jam operasional, nomor telepon, dan alamat yang akurat. Review dari pelanggan sangat berpengaruh ke ranking lokal." },
      { type: "p", text: "SEO adalah marathon, bukan sprint. Konsistensi lebih penting dari taktik viral. Posting konten yang berguna secara rutin, dan hasilnya akan terasa dalam 3–6 bulan." },
    ],
  },
  {
    slug: "kapan-bisnis-butuh-website-custom",
    title: "Kapan bisnis kamu butuh website custom, bukan template?",
    excerpt: "Template bisa jalan untuk banyak kasus — tapi ada titik di mana custom jadi investasi yang lebih masuk akal secara bisnis.",
    category: "bisnis",
    categoryLabel: "Bisnis",
    date: "2026-07-15",
    readTime: 4,
    coverColor: "#fef9e8",
    content: [
      { type: "p", text: "Pertanyaan ini sering kami terima dari calon klien yang bingung antara pilih template murah atau invest di desain custom. Jawaban jujurnya: keduanya valid, tergantung situasi bisnis kamu saat ini." },
      { type: "h2", text: "Kapan Template Sudah Cukup" },
      { type: "ul", items: [
        "Bisnis baru yang belum membuktikan product-market fit",
        "Budget terbatas dan kecepatan launch adalah prioritas",
        "Kebutuhan website standar: company profile, portofolio sederhana, landing page campaign",
        "Kamu nyaman mengelola sendiri dan tidak butuh fitur khusus",
      ]},
      { type: "h2", text: "Tanda Kamu Butuh Custom" },
      { type: "ul", items: [
        "Bisnis kamu sudah punya revenue stabil dan website adalah channel akuisisi utama",
        "Kompetitor kamu punya website yang jauh lebih baik dan kamu kehilangan klien karena itu",
        "Kamu butuh integrasi sistem yang tidak didukung template (CRM, ERP, custom workflow)",
        "Brand kamu unik dan template apapun terasa 'tidak pas'",
        "Performa (kecepatan, konversi) sudah jadi bottleneck bisnis",
      ]},
      { type: "quote", text: "Website custom bukan tentang ego — ini tentang ROI. Kalau setiap 10 pengunjung website kamu menghasilkan 1 deal, dan rata-rata deal kamu Rp 5 juta, meningkatkan conversion rate 1% bisa berarti jutaan rupiah per bulan." },
      { type: "h2", text: "Framework Keputusan Kami" },
      { type: "p", text: "Sebelum rekomendasikan apapun ke klien, kami tanya tiga pertanyaan: Berapa nilai rata-rata satu customer? Berapa target customer baru per bulan dari website? Berapa conversion rate website saat ini?" },
      { type: "callout", text: "Kalau potensi revenue dari website kamu di atas Rp 50 juta per tahun, investasi di custom design biasanya payback dalam 6–12 bulan. Di bawah itu, template yang dioptimasi dengan baik sudah lebih dari cukup." },
    ],
  },
  {
    slug: "tipografi-web-yang-mudah-dibaca",
    title: "Tipografi web yang mudah dibaca: panduan praktis",
    excerpt: "Ukuran, spasi baris, dan kontras warna — tiga variabel yang menentukan apakah pengunjung betah baca atau langsung kabur.",
    category: "desain",
    categoryLabel: "Desain",
    date: "2026-07-10",
    readTime: 5,
    coverColor: "#f0e8fe",
    content: [
      { type: "p", text: "Tipografi yang baik tidak terlihat — kamu hanya merasakannya ketika membaca terasa nyaman dan mudah. Sebaliknya, tipografi yang buruk langsung terasa meski kamu tidak bisa mengartikulasikannya. Mari kita bongkar komponen-komponennya." },
      { type: "h2", text: "Ukuran Font: Lebih Besar dari yang Kamu Kira" },
      { type: "p", text: "Standar minimum body text untuk web adalah 16px, tapi banyak desainer masih pakai 14px karena 'terlihat lebih rapi di layar besar'. Masalahnya, 60% pengguna kamu membuka di mobile di bawah kondisi cahaya yang bervariasi." },
      { type: "callout", text: "Rekomendasi: 16–18px untuk body text, 14px untuk caption/label kecil, dan jangan turun di bawah 12px untuk teks apapun yang perlu dibaca." },
      { type: "h2", text: "Line Height: Ruang Napas untuk Teks" },
      { type: "p", text: "Line height (jarak antar baris) yang terlalu rapat membuat teks terasa sesak dan sulit diikuti dari satu baris ke baris berikutnya. Yang terlalu lebar membuat koneksi antar kalimat hilang." },
      { type: "ul", items: [
        "Body text: line-height 1.5–1.7",
        "Heading besar: line-height 1.1–1.2 (lebih rapat, lebih impactful)",
        "Teks kecil (caption, label): line-height 1.4",
      ]},
      { type: "h2", text: "Kontras Warna: Aksesibilitas Bukan Opsional" },
      { type: "p", text: "WCAG menetapkan minimum contrast ratio 4.5:1 untuk body text. Tapi ini minimum — untuk pengalaman baca yang nyaman, bidik 7:1. Teks abu-abu terang di background putih mungkin terlihat elegan di mockup, tapi menyiksa di dunia nyata." },
      { type: "h2", text: "Lebar Kolom: Batas yang Sering Diabaikan" },
      { type: "p", text: "Seperti yang dibahas di artikel tentang layout, lebar teks yang ideal adalah 60–75 karakter per baris. Untuk website, ini biasanya berarti max-width sekitar 680–720px untuk kolom konten." },
      { type: "quote", text: "Typography is the voice of text. When it's done right, you don't notice it — you just feel that the content is clear and trustworthy.", author: "Ellen Lupton" },
    ],
  },
  {
    slug: "nextjs-vs-wordpress-2026",
    title: "Next.js vs WordPress di 2026: mana yang lebih cocok untuk klien UMKM?",
    excerpt: "Perbandingan jujur dari pengalaman kami mengelola puluhan project — performa, biaya maintenance, dan kemudahan klien pakai.",
    category: "development",
    categoryLabel: "Development",
    date: "2026-07-05",
    readTime: 8,
    coverColor: "#e8f8fe",
    content: [
      { type: "p", text: "Kami sudah mengerjakan project di kedua platform — WordPress untuk lebih dari 80 klien, Next.js untuk 40+ klien sejak 2022. Ini bukan opini teori, tapi berdasarkan pengalaman nyata termasuk support, maintenance, dan feedback langsung dari klien non-teknis." },
      { type: "h2", text: "WordPress: Masih Relevan di 2026" },
      { type: "p", text: "WordPress masih menguasai 43% dari seluruh website di internet. Angka itu bukan kebetulan. Ekosistemnya matang, pilihan tema dan plugin sangat luas, dan yang paling penting — hampir semua klien non-teknis bisa mengelola konten sendiri setelah training 30 menit." },
      { type: "ul", items: [
        "Keunggulan: ekosistem plugin terbesar, editor Gutenberg yang semakin baik, biaya hosting rendah",
        "Keunggulan: klien bisa update konten sendiri tanpa developer",
        "Kelemahan: keamanan (perlu update rutin dan monitoring aktif)",
        "Kelemahan: performa default buruk tanpa optimasi ekstra",
        "Kelemahan: technical debt menumpuk seiring waktu",
      ]},
      { type: "h2", text: "Next.js: Investasi untuk Skala" },
      { type: "p", text: "Next.js dengan App Router adalah pilihan kami untuk klien yang serius soal performa dan skalabilitas. Static generation, built-in image optimization, dan edge runtime membuat website Next.js bisa mencapai Core Web Vitals score yang sulit dicapai WordPress tanpa plugin premium." },
      { type: "ul", items: [
        "Keunggulan: performa out-of-the-box jauh lebih baik",
        "Keunggulan: DX yang excellent, ekosistem modern",
        "Keunggulan: tidak ada security vulnerability dari plugin pihak ketiga",
        "Kelemahan: klien non-teknis tidak bisa update konten tanpa CMS tambahan (Sanity, Contentful)",
        "Kelemahan: biaya development dan maintenance lebih tinggi",
      ]},
      { type: "h2", text: "Rekomendasi Kami untuk UMKM" },
      { type: "callout", text: "Pakai WordPress kalau: klien perlu update konten rutin secara mandiri, budget development terbatas, atau website-nya relatif sederhana (company profile, blog). Pakai Next.js kalau: performa adalah prioritas, ada budget untuk CMS terpisah, atau website akan berkembang jadi aplikasi web yang lebih kompleks." },
      { type: "p", text: "Tidak ada jawaban universal. Yang terpenting adalah kecocokan dengan kebutuhan dan kapabilitas tim klien, bukan tren teknologi." },
    ],
  },
  {
    slug: "studi-kasus-toko-kue",
    title: "Dari Instagram ke website: studi kasus toko kue Bandung",
    excerpt: "Bagaimana satu halaman landing sederhana membantu toko kue kecil mendapat 40 pesanan baru dalam bulan pertama.",
    category: "studi-kasus",
    categoryLabel: "Studi Kasus",
    date: "2026-06-28",
    readTime: 5,
    coverColor: "#fef0e8",
    content: [
      { type: "p", text: "Dina menjalankan toko kue rumahan di Bandung. Seluruh pemasarannya lewat Instagram dengan 12.000 followers — dan itu sudah cukup sampai dia kewalahan mengelola DM pesanan yang tidak terstruktur." },
      { type: "h2", text: "Masalah yang Perlu Dipecahkan" },
      { type: "ul", items: [
        "Pesanan masuk lewat DM tidak terstruktur — sering typo lokasi, tanggal, atau jenis kue",
        "Tidak ada cara mudah untuk tampilkan harga dan varian produk",
        "Repeat customer kesulitan re-order karena tidak ingat detail produk",
        "Dina menghabiskan 2–3 jam per hari hanya untuk reply DM dan konfirmasi pesanan",
      ]},
      { type: "h2", text: "Solusi: Landing Page Minimal yang Tepat Sasaran" },
      { type: "p", text: "Kami tidak bikin toko online penuh — itu overkill untuk situasi Dina. Yang dia butuhkan adalah halaman yang menjawab tiga pertanyaan: apa yang dijual, berapa harganya, dan bagaimana cara pesan." },
      { type: "p", text: "Dalam 5 hari kerja, kami buat landing page dengan katalog produk yang bisa di-filter, form pemesanan sederhana yang tersambung ke WhatsApp dengan format yang sudah diisi otomatis, dan galeri testimoni dari screenshot review Instagram." },
      { type: "h2", text: "Hasilnya Setelah 30 Hari" },
      { type: "ul", items: [
        "40 pesanan baru yang datang langsung dari website (bukan Instagram)",
        "Waktu yang dihabiskan untuk reply DM turun dari 2–3 jam ke 30 menit per hari",
        "Rata-rata nilai pesanan naik 22% karena pelanggan bisa lihat katalog lengkap",
        "3 pesanan catering dari klien korporat yang tidak akan masuk lewat DM Instagram",
      ]},
      { type: "quote", text: "Websitenya simple banget, tapi itu yang aku butuhkan. Sekarang orang bisa lihat semua produk dan langsung order tanpa bolak-balik chat.", author: "Dina, pemilik Dapur Manis Bandung" },
      { type: "callout", text: "Pelajaran utama: solusi yang tepat tidak selalu yang paling kompleks. Identifikasi bottleneck utama bisnis kamu, dan selesaikan itu dulu. Satu halaman yang tepat sasaran bisa lebih berdampak dari toko online lengkap yang rumit." },
    ],
  },
  {
    slug: "google-search-console-pemula",
    title: "Cara baca Google Search Console untuk pemula",
    excerpt: "Data impressi, klik, dan posisi — ini cara membacanya tanpa perlu jadi ahli SEO dulu.",
    category: "seo",
    categoryLabel: "SEO",
    date: "2026-06-20",
    readTime: 6,
    coverColor: "#eafee8",
    content: [
      { type: "p", text: "Google Search Console (GSC) adalah tools gratis paling underrated untuk pemilik website. Banyak yang sudah setup tapi tidak tahu cara baca datanya. Padahal dari GSC, kamu bisa tahu persis halaman mana yang performanya bagus, dan keyword apa yang mendatangkan pengunjung." },
      { type: "h2", text: "Empat Metrik Utama yang Perlu Dipahami" },
      { type: "ul", items: [
        "Impressi: berapa kali URL kamu muncul di hasil pencarian (meski tidak diklik)",
        "Klik: berapa kali pengunjung benar-benar mengklik URL kamu",
        "CTR (Click-Through Rate): persentase impressi yang berujung klik. Rata-rata 2–5% sudah bagus",
        "Posisi rata-rata: peringkat rata-rata kamu untuk query tertentu. Posisi 1–3 adalah sweet spot",
      ]},
      { type: "h2", text: "Laporan Performance: Cara Membacanya" },
      { type: "p", text: "Buka GSC → Performance → pilih rentang waktu 3 bulan terakhir. Kamu akan lihat grafik total klik dan impressi. Yang lebih menarik: scroll ke bawah dan pilih tab 'Queries' — ini daftar kata kunci yang membuat website kamu muncul di Google." },
      { type: "callout", text: "Cari query yang impressi-nya tinggi tapi CTR-nya rendah (di bawah 2%). Itu artinya kamu sudah muncul di hasil pencarian, tapi orang tidak tertarik klik. Perbaiki title tag dan meta description halaman tersebut." },
      { type: "h2", text: "Coverage Report: Cek Halaman yang Bermasalah" },
      { type: "p", text: "Di menu Coverage (atau Indexing → Pages), kamu bisa lihat halaman mana yang berhasil diindex Google dan mana yang tidak. Error 404, redirect yang rusak, atau halaman yang di-block oleh robots.txt semuanya akan muncul di sini." },
      { type: "h2", text: "Core Web Vitals di GSC" },
      { type: "p", text: "GSC juga punya laporan Core Web Vitals berdasarkan data pengguna nyata (bukan lab test). Ini lebih akurat dari Lighthouse karena mencerminkan pengalaman pengguna dengan device dan koneksi yang bervariasi." },
      { type: "p", text: "Cukup 15 menit seminggu untuk review GSC sudah memberi kamu insight yang jauh lebih berharga dari kebanyakan tools SEO berbayar." },
    ],
  },
  {
    slug: "dark-mode-ux-pertimbangan",
    title: "Dark mode di website: kapan perlu, kapan tidak?",
    excerpt: "Bukan semua website butuh dark mode — ini pertimbangan UX dan teknis sebelum kamu memutuskan implementasi.",
    category: "desain",
    categoryLabel: "Desain",
    date: "2026-06-14",
    readTime: 4,
    coverColor: "#e8e8fe",
    content: [
      { type: "p", text: "Dark mode jadi fitur yang hampir semua developer ingin implementasikan setelah macOS dan iOS mempopulerkannya. Tapi dari perspektif UX dan bisnis, keputusan ini tidak sesederhana mengganti background dari putih ke hitam." },
      { type: "h2", text: "Kapan Dark Mode Benar-Benar Bermanfaat" },
      { type: "ul", items: [
        "Aplikasi yang digunakan dalam kondisi cahaya rendah (entertainment, musik, video)",
        "Tool developer atau editor kode — mata terasa lebih nyaman untuk sesi panjang",
        "Platform dengan konten visual heavy di mana warna konten lebih menonjol di background gelap",
        "Brand yang memang identitasnya dark/premium (luxury, gaming, tech)",
      ]},
      { type: "h2", text: "Kapan Dark Mode Bisa Kontraproduktif" },
      { type: "p", text: "Untuk website bisnis pada umumnya — toko online, company profile, landing page — dark mode sering membuat teks lebih sulit dibaca dan elemen UI lebih sulit diparse. Otak manusia sudah terlatih membaca teks gelap di atas background terang." },
      { type: "ul", items: [
        "E-commerce: foto produk biasanya diambil dengan background putih/terang",
        "Website dengan banyak teks: kontras yang baik lebih mudah dicapai di light mode",
        "Target audience yang lebih tua: sensitivitas kontras menurun seiring usia",
      ]},
      { type: "h2", text: "Kompleksitas Teknis yang Sering Diremehkan" },
      { type: "p", text: "Implementasi dark mode yang benar bukan hanya balik warna. Kamu perlu pastikan semua gambar, icon, dan ilustrasi masih terlihat baik di background gelap. Shadow yang bekerja di light mode tidak otomatis bekerja di dark mode." },
      { type: "callout", text: "Estimasi realistis: implementasi dark mode yang proper membutuhkan 30–50% waktu tambahan dari development awal. Kalau kamu tidak siap untuk itu, lebih baik tidak implementasi setengah-setengah." },
      { type: "p", text: "Rekomendasi kami: ikuti preferensi sistem pengguna dengan prefers-color-scheme jika kamu memang commit untuk implement keduanya dengan benar. Kalau tidak, pilih satu mode dan optimasi sepenuhnya." },
    ],
  },
  {
    slug: "harga-website-bisnis-2026",
    title: "Berapa harga website yang wajar untuk bisnis di 2026?",
    excerpt: "Breakdown jujur komponen biaya website — dari domain, hosting, desain, sampai maintenance tahunan.",
    category: "bisnis",
    categoryLabel: "Bisnis",
    date: "2026-06-08",
    readTime: 5,
    coverColor: "#fefee8",
    content: [
      { type: "p", text: "Pertanyaan paling sering kami terima dari calon klien: 'Berapa harga website yang wajar?' Jawabannya sangat tergantung kebutuhan, tapi kami akan berikan breakdown yang jujur berdasarkan harga pasar Indonesia di 2026." },
      { type: "h2", text: "Komponen Biaya yang Perlu Diperhitungkan" },
      { type: "h3", text: "Domain & Hosting (Biaya Tahunan)" },
      { type: "ul", items: [
        "Domain .id: Rp 150.000–250.000/tahun",
        "Domain .com: Rp 200.000–300.000/tahun",
        "Shared hosting entry level: Rp 300.000–600.000/tahun",
        "VPS (untuk website dengan traffic lebih tinggi): Rp 500.000–2.000.000/tahun",
        "Vercel/Netlify Pro (untuk Next.js): mulai Rp 300.000/bulan",
      ]},
      { type: "h3", text: "Biaya Development" },
      { type: "ul", items: [
        "Template WordPress + kustomisasi: Rp 1.500.000–5.000.000",
        "Company profile custom: Rp 5.000.000–15.000.000",
        "Landing page premium: Rp 3.000.000–8.000.000",
        "E-commerce sederhana: Rp 8.000.000–20.000.000",
        "Aplikasi web custom: Rp 20.000.000+",
      ]},
      { type: "h2", text: "Red Flags: Harga Terlalu Murah" },
      { type: "p", text: "Website company profile yang ditawarkan di bawah Rp 500.000 hampir pasti menggunakan template gratisan tanpa kustomisasi berarti, tidak termasuk support, dan mungkin akan hilang setelah project selesai." },
      { type: "callout", text: "Patokan kami: harga yang wajar untuk company profile dengan kualitas yang bisa bersaing di pasar Indonesia adalah Rp 3.000.000–8.000.000 untuk one-time cost, plus Rp 500.000–1.500.000/tahun untuk hosting dan maintenance." },
      { type: "h2", text: "Investasi vs Pengeluaran" },
      { type: "p", text: "Cara paling tepat untuk melihat biaya website bukan sebagai expense, tapi sebagai investasi. Kalau website kamu menghasilkan satu lead baru per bulan dengan nilai deal rata-rata Rp 5 juta, website seharga Rp 8 juta sudah payback dalam 2 bulan." },
    ],
  },
  {
    slug: "animasi-web-tanpa-hambat-performa",
    title: "Animasi web yang tidak menghambat performa",
    excerpt: "CSS transform vs JavaScript animation — panduan memilih pendekatan yang terasa smooth tanpa mengorbankan Lighthouse score.",
    category: "development",
    categoryLabel: "Development",
    date: "2026-06-01",
    readTime: 6,
    coverColor: "#fee8f8",
    content: [
      { type: "p", text: "Animasi yang smooth bikin website terasa premium. Tapi animasi yang tidak diimplementasikan dengan benar bisa langsung menghancurkan Core Web Vitals dan membuat pengguna frustrasi. Ini panduan praktis untuk mendapat keduanya: animasi yang bagus dan performa yang baik." },
      { type: "h2", text: "Pahami Rendering Pipeline Browser" },
      { type: "p", text: "Browser merender halaman melalui beberapa tahap: Style → Layout → Paint → Composite. Animasi yang memicu Layout (seperti mengubah width, height, atau position) paling mahal secara performa. Animasi yang hanya memicu Composite (transform dan opacity) hampir gratis." },
      { type: "callout", text: "Aturan emas: animasikan HANYA transform (translate, scale, rotate) dan opacity. Hindari animasi pada width, height, top, left, margin, atau padding — properti-properti ini memicu layout recalculation." },
      { type: "h2", text: "CSS Animation vs JavaScript Animation" },
      { type: "h3", text: "Gunakan CSS untuk Animasi Sederhana" },
      { type: "ul", items: [
        "Hover effects, fade in/out, slide transitions",
        "Animasi yang tidak perlu dikontrol secara dinamis",
        "Lebih mudah dibaca dan di-maintain",
        "Browser bisa optimasi di compositor thread",
      ]},
      { type: "h3", text: "Gunakan JavaScript (GSAP/Framer Motion) untuk Animasi Kompleks" },
      { type: "ul", items: [
        "Animasi yang perlu dikontrol berdasarkan state atau interaksi kompleks",
        "Sequence animasi yang panjang",
        "Physics-based animation (spring, bounce)",
        "Scroll-linked animations",
      ]},
      { type: "h2", text: "will-change: Senjata Bermata Dua" },
      { type: "p", text: "Property will-change memberi hint ke browser untuk mempersiapkan elemen di compositor layer. Ini bisa membuat animasi lebih smooth, tapi jika dipakai berlebihan — di semua elemen — justru memakan memori dan memperlambat halaman." },
      { type: "h2", text: "Selalu Hormati prefers-reduced-motion" },
      { type: "p", text: "Sekitar 35% pengguna iOS mengaktifkan Reduce Motion karena vestibular disorders atau preferensi personal. Kamu wajib menyediakan fallback:" },
      { type: "ul", items: [
        "@media (prefers-reduced-motion: reduce) { /* matikan atau kurangi animasi */ }",
        "Jangan hanya mematikan animasi — pastikan konten masih visible (opacity tetap 1)",
        "Animasi yang informatif (loading spinner) boleh tetap ada",
      ]},
      { type: "p", text: "Animasi yang baik tidak diperhatikan — pengguna hanya merasakan website yang terasa responsive dan polished. Kalau animasi kamu yang paling diingat pengunjung, kemungkinan besar itu terlalu berlebihan." },
    ],
  },
];

export function formatDate(iso: string): string {
  return new Date(iso).toLocaleDateString("id-ID", {
    day: "numeric",
    month: "short",
    year: "numeric",
  });
}
